name: shelfie
description: "Shelfie - A personal bookshelf management app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  built_collection: any
  built_value: any
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.6
  ferry: ^0.16.1+2
  ferry_flutter: ^0.9.1+1
  ferry_hive_store: ^0.6.0+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.2
  font_awesome_flutter: 10.6.0
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.4
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  gql_exec: any
  gql_http_link: ^1.2.0
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  mobile_scanner: ^6.0.2
  palette_generator: ^0.3.3+4
  riverpod_annotation: ^2.3.5
  share_plus: ^10.1.3
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.8
  ferry_generator: ^0.12.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.4
  riverpod_generator: ^2.3.11
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/google_fonts/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#0A0A0A"
  image: assets/icons/splash_icon.png
  android_12:
    color: "#0A0A0A"
    image: assets/icons/splash_icon.png
